version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - APP_ROOT=${CLIENT_ROOT}
    container_name: client
    restart: always
    command: "node .output/server/index.mjs"
    volumes:
      - ./src/client:/usr/local/src/client
    networks:
      - internal
  mysql:
    build:
      context: docker/mysql
    container_name: mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    networks:
      - internal
  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - internal

networks:
  internal:
  external:
    external: true
